#KukaButtonGymEnv-v0:
#  # Base path to SRL log folder
#  log_folder: srl_zoo/logs/RL_test/
#  # Path to the different trained SRL models
#  autoencoder: autoencoder_cnn_ST_DIM3_SEED0_NOISE0_EPOCHS1_BS32/srl_model.pth
#  vae: vae_cnn_ST_DIM3_SEED0_NOISE0_EPOCHS1_BS32/srl_model.pth
#  supervised: baselines/supervised_cnn_SEED0_EPOCHS1_BS32/srl_supervised_model.pth
#  pca: baselines/pca_ST_DIM5/pca.pkl
#  robotic_priors: priors_cnn_ST_DIM3_SEED0_NOISE0_EPOCHS1_BS32/srl_model.pth
#  inverse: inverse_cnn_ST_DIM3_SEED0_NOISE0_EPOCHS1_BS32/srl_model.pth
#  forward: forward_cnn_ST_DIM3_SEED0_NOISE0_EPOCHS1_BS32/srl_model.pth
#  multi_view_srl: triplet_cnn_ST_DIM3_SEED0_NOISE0_EPOCHS1_BS32/srl_model.pth
#  srl_combination: vae_inverse_forward_cnn_ST_DIM3_SEED0_NOISE0_EPOCHS1_BS32/srl_model.pth

Baxter-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/baxter_real_2/
  # Path to the different trained SRL models
  autoencoder: 19-02-07_02h02_20_custom_cnn_ST_DIM2_autoencoder/srl_model.pth
# vae: 19-01-30_16h33_47_custom_cnn_ST_DIM2_vae/srl_model.pth
# supervised: baselines/supervised_resnet_SEED1_EPOCHS50_BS32/srl_supervised_model.pth
# pca: baselines/pca_ST_DIM5/pca.pkl
  inverse: 19-02-07_23h05_52_custom_cnn_ST_DIM2_inverse/srl_model.pth
# forward: 19-01-31_01h52_23_custom_cnn_ST_DIM2_forward/srl_model.pth
# multi_view_srl: 19-01-31_14h46_08_custom_cnn_ST_DIM2_triplet/srl_model.pth
# srl_combination: 19-01-29_22h45_33_custom_cnn_ST_DIM2_autoencoder_inverse/srl_model.pth
  reward: 19-02-07_23h45_28_custom_cnn_ST_DIM2_reward/srl_model.pth
  dae: 19-02-08_00h15_14_custom_cnn_ST_DIM2_dae/srl_model.pth
  robotic_priors: 19-02-07_23h58_39_custom_cnn_ST_DIM2_priors/srl_model.pth
