Baxter-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/baxter_real_2/
  # Path to the different trained SRL models
  autoencoder: 19-02-07_02h02_20_custom_cnn_ST_DIM2_autoencoder/srl_model.pth
  vae: 19-02-08_00h41_22_custom_cnn_ST_DIM2_vae/srl_model.pth
# supervised: baselines/supervised_resnet_SEED1_EPOCHS50_BS32/srl_supervised_model.pth
# pca: baselines/pca_ST_DIM5/pca.pkl
  inverse: 19-02-07_23h05_52_custom_cnn_ST_DIM2_inverse/srl_model.pth
# forward: 19-01-31_01h52_23_custom_cnn_ST_DIM2_forward/srl_model.pth
# multi_view_srl: 19-01-31_14h46_08_custom_cnn_ST_DIM2_triplet/srl_model.pth
  srl_combination: 19-02-08_01h05_03_custom_cnn_ST_DIM2_inverse_autoencoder/srl_model.pth
  srl_splits: 19-02-12_14h55_16_custom_cnn_ST_DIM22_autoencoder_inverse/srl_model.pth
  reward: 19-02-07_23h45_28_custom_cnn_ST_DIM2_reward/srl_model.pth
  dae: 19-02-08_00h15_14_custom_cnn_ST_DIM2_dae/srl_model.pth
  robotic_priors: 19-02-07_23h58_39_custom_cnn_ST_DIM2_priors/srl_model.pth

# inverse-autoencoder 19-02-08_01h05_03_custom_cnn_ST_DIM2_inverse_autoencoder
# episode-prior 19-02-08_01h32_58_custom_cnn_ST_DIM2_episode-prior
# episode-prior 19-02-08_01h45_29_custom_cnn_ST_DIM2_episode-prior
# reward-prior 19-02-08_01h59_53_custom_cnn_ST_DIM2_reward-prior
# autoencoder-inverse split 19-02-12_02h39_30_custom_cnn_ST_DIM22_autoencoder_inverse
# reward-inverse-forward 19-02-12_14h38_08_custom_cnn_ST_DIM52_reward_inverse_forward
# autoencoder-inverse 19-02-12_14h55_16_custom_cnn_ST_DIM22_autoencoder_inverse
# autoencoder-inverse-reward 19-02-14_01h11_30_custom_cnn_ST_DIM25_autoencoder_inverse_reward

