Baxter-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/baxter_real_2/
  # Path to the different trained SRL models
  autoencoder: 19-03-26_14h52_55_custom_cnn_ST_DIM2_autoencoder/srl_model.pth
  vae: 19-03-26_20h30_32_custom_cnn_ST_DIM2_vae/srl_model.pth
# supervised: baselines/supervised_resnet_SEED1_EPOCHS50_BS32/srl_supervised_model.pth
# pca: baselines/pca_ST_DIM5/pca.pkl
  inverse: 19-03-26_15h49_33_custom_cnn_ST_DIM2_inverse/srl_model.pth
  forward: 19-03-26_23h07_22_custom_cnn_ST_DIM2_forward/srl_model.pth
# multi_view_srl: 19-01-31_14h46_08_custom_cnn_ST_DIM2_triplet/srl_model.pth
  srl_combination: 19-03-27_15h02_03_custom_cnn_ST_DIM2_inverse_autoencoder/srl_model.pth
  srl_splits: 19-03-26_23h43_25_custom_cnn_ST_DIM22_autoencoder_inverse/srl_model.pth
  reward: 19-03-26_22h29_07_custom_cnn_ST_DIM2_reward/srl_model.pth
  dae: 19-03-26_16h29_36_custom_cnn_ST_DIM2_dae/srl_model.pth
  robotic_priors: 19-03-27_01h28_38_custom_cnn_ST_DIM2_priors/srl_model.pth
  pca: baselines/pca_ST_DIM3/pca.pkl
  supervised: baselines/supervised_resnet_SEED1_EPOCHS50_BS32/srl_supervised_model.pth
  autoencoder_reward: 19-04-07_15h24_23_custom_cnn_ST_DIM2_reward_autoencoder/srl_model.pth
  autoencoder_forward: 19-04-07_17h00_44_custom_cnn_ST_DIM2_autoencoder_forward/srl_model.pth
  random: 19-04-08_03h37_33_custom_cnn_ST_DIM2_random/srl_model.pth
  reward_inverse: 19-04-08_03h38_38_custom_cnn_ST_DIM2_inverse_reward/srl_model.pth
  random_inverse: 19-04-08_15h05_21_custom_cnn_ST_DIM2_inverse_random/srl_model.pth
  srl_3_splits: 19-04-08_16h28_08_custom_cnn_ST_DIM52_reward_inverse_forward/srl_model.pth
  srl_split_forward: 19-04-08_23h56_11_custom_cnn_ST_DIM52_reward_forward

#  episode_prior: 19-03-27_02h26_09_custom_cnn_ST_DIM2_episode-prior/srl_supervised_model.pth
#  reward_prior: 19-03-27_12h21_24_custom_cnn_ST_DIM2_reward-prior/srl_supervised_model.pth

